### ISSUE TITLE
Error on import { Analytics, PageHit } from 'expo-analytics';

### ISSUE THREAD

**Issue by MarcHbb** [ryanvanderpol/expo-analytics#84]
I installed the node module, and did just a simple import but I always getting this error : 

`TypeError: undefined is not an object (evaluating '_expoModulesCore.NativeModulesProxy.ExponentConstants')
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0`

SDK version : 42

**Comment by eliransu** [comment]
same here

**Comment by flash29** [comment]
Running into the same problem

Did you find a solution or a work around for this ?
 
let me know if you have a solution.
